spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bn-profile-service
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

minio:
  url: http://minio:9000
  accessKey: admin
  secretKey: 12345678
  bucket: bn-profile-service
