CREATE TABLE IF NOT EXISTS public.company
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    about          TEXT,
    is_active      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_reliability BOOLEAN      NOT NULL DEFAULT FALSE,
    vk_link        VARCHAR(512),
    website_link   VARCHAR(512),
    ogrn           VARCHAR(15),
    inn            VARCHAR(12),
    kpp            VARCHAR(9),
    okpo           VARCHAR(10),
    legal_address  VARCHAR(512),


    CONSTRAINT uq_company_ogrn UNIQUE (ogrn),
    CONSTRAINT uq_company_inn UNIQUE (inn),
    CONSTRAINT uq_company_kpp UNIQUE (kpp),
    CONSTRAINT uq_company_okpo UNIQUE (okpo)
);

CREATE TABLE IF NOT EXISTS public.contact
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    last_name    VARCHAR(255),
    patronymic   VARCHAR(255),
    position     VARCHAR(255),
    phone_number VARCHAR(64),
    company_id   BIGINT NOT NULL,

    CONSTRAINT fk_contact_company
        FOREIGN KEY (company_id)
            REFERENCES public.company (id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_contact_company_id ON public.contact (company_id);

CREATE TABLE IF NOT EXISTS public.product
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    company_id BIGINT       NOT NULL,

    CONSTRAINT fk_product_company
        FOREIGN KEY (company_id)
            REFERENCES public.company (id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_product_company_id ON public.product (company_id);
